### ISSUE TITLE
Won't run on my PC

### ISSUE THREAD

**Issue by charliegc4** [SIRprise/SSD-LED#1]
Downloaded the exe file located at https://github.com/SIRprise/SSD-LED/tree/master/SSD-LED/bin/Release

When I try to run it on Windows 10 1903 18362.535 I get the error: This app can't run on your PC. To find a version for your PC, check with the software publisher.

![image](https://user-images.githubusercontent.com/43522889/71513484-314afe00-28a3-11ea-8d48-39b4901cac02.png)

**Comment by SIRprise** [comment]
Hmm, that's interesting!
Do you run it on a 32 bit installation or an ARM processor?
Is side-loading enabled? - see Fix 3+4 at
[https://www.easeus.com/todo-backup-resource/this-app-cant-run-on-your-pc-in-windows-10.html]

My setup is:
Microsoft Windows 10 Pro x64 (1909)
10.0.18363 Build 18363

I tested it with all compatibility options (Windows 8.1, Win 7 etc.) and the program is executed correctly.

**Comment by charliegc4** [comment]
64bit version of Windows. 

Sideloading is enabled, and I already tried with SmartScreen disabled as well as running as Administrator, and on all the compatibility options. There is no difference.

Are there any dependencies?

**Comment by charliegc4** [comment]
Or is the application maybe device dependent? I am using a Samsung M.2 SSD.

**Comment by SIRprise** [comment]
There are no special dependencies to run. I'm also using a M.2 SSD.
The tool uses the same data as "perfmon". The parameters are used are accessed by english string names - that should be the same in nearly all windows versions. (I'm using a german Windows).

If you have the possibility, you could compile it by yourself.
You need VS2013 or above and do the following:
- right click on IndicatorIcon.cs and exclude it from project (the file is not used yet)
- select debug right from the start-button
- click build -> rebuild solution
- click start
- report line number + error here (error at the line the program stopps running)

I just tested it with Visual Studio Community 2013 and I developed it with VS2017 Community.

**Comment by 4xMeister** [comment]
App is NOT device dependent. It doesn't know and doesn't care what kind of drive you are running.
Installs & runs fine on Windows 10 v1909 x64

**Comment by charliegc4** [comment]
Device dependent, I was referring to mSATA, M.2, PCI-E etc. Some applications are specific about the hardware format\driver, which IS NOT the same for these devices.

Both you and SIRprise are running 1909, so I guess it just doesn't run on 1903 then. What a pity.

**Comment by charliegc4** [comment]
It has something to do with the way the file is downloaded. If I right-click on the file in the link above and choose Save As, I get the following:

![image](https://user-images.githubusercontent.com/43522889/71545586-b7e00800-2995-11ea-86db-87d393a07f44.png)

If I go to https://github.com/SIRprise/SSD-LED and click the download button, I get the whole zip file, but the exe file is the following:

![image](https://user-images.githubusercontent.com/43522889/71545607-dba34e00-2995-11ea-9311-da3e3f737b25.png)

The first is almost 3 times the size, and that is the one that does not work. The one extracted from the zip works.

**Comment by SIRprise** [comment]
Nice to see it worked in the end. :-)
You could open your 80KByte file via text editor and see it is the html-page of github...
If you want to download one file only you have to left click on it and it shows the html you downloaded:
[https://github.com/SIRprise/SSD-LED/blob/master/SSD-LED/bin/Release/SSD-LED.exe](url)
If you right click on "view raw" and save it, you should have the file you wanted to.
