### ISSUE TITLE
Feature Request:  Add option in application to start/stop with Windows start/shutdown?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [SIRprise/SSD-LED#10]
Feature Request:  Add option in application to run with Windows start?  Maybe a system task that starts and stops application on Windows system start and stop events?

**Comment by SIRprise** [comment]
There is an option to autostart it:
![grafik](https://user-images.githubusercontent.com/5807446/135514015-ba4b3e91-6a76-40c0-858a-a753e8e8309d.png)

**Comment by Nodi-Rubrum** [comment]
Ah... cool.  Thx.
