### ISSUE TITLE
Installs and Runs but Preferences will not display.

### ISSUE THREAD

**Issue by buntyfanshaw** [SIRprise/SSD-LED#2]
Win10 64 Build 19536.rs_prerelease

App loads and systray icon flashes as expected, but when I right click on the systray icon and select Preferences, the dialog flashes up momentarily and then disappears.

**Comment by 4xMeister** [comment]
Double Click instead of Right Click and the preferences come up fine! :-)

**Comment by SIRprise** [comment]
Thanks for reporting!
It seems the notify-icon click-event is also triggered if preferences was clicked, so it is triggered two times. Another side effect is that the window comes up on clicking exit. I will fix it... just a sec.

**Comment by SIRprise** [comment]
Fixed with commit [https://github.com/SIRprise/SSD-LED/commit/b2f43c9918d0b0086e88d37c85e760ff84c6448f](url)
