### ISSUE TITLE
Doesn't run on Win 10 Pro

### ISSUE THREAD

**Issue by bmeacham** [SIRprise/SSD-LED#4]
"This app can't run on your PC."  Windows 10 Pro version 1909 build 18363.535 64-bit. Dell Latitude 7390, 16 gig RAM, 1 TB SSD.

**Comment by bmeacham** [comment]
When I click the Download button I get a zero-byte file.  I presume that's why it won't run. How can I download the executable?

**Comment by SIRprise** [comment]
I could reproduce this problem on another computer with Firefox. I assume another browser doesn't produce that 0 byte files.
I also made an official release you can find here [https://github.com/SIRprise/SSD-LED/releases](url)

**Comment by SIRprise** [comment]
#1 is a similar issue

**Comment by bmeacham** [comment]
Right, Firefox produces a zero-byte file, Vivaldi produces a 27 KB file.  Very strange.  Thanks for looking into it.

**Comment by bmeacham** [comment]
OK, closing this one.
