### ISSUE TITLE
Enhancement request - start at Windows startup

### ISSUE THREAD

**Issue by bmeacham** [SIRprise/SSD-LED#5]
Enhancement request: add an option to make it start when Windows starts. I figured out how to do it by putting a shortcut in C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup, but it would be nice to be able to do it from the Preferences pane.

**Comment by SIRprise** [comment]
Option can be selected in new version 1.0.4 on new second tab. It is using registry autostart instead of your suggestion.
It also has a setup (but is not yet searching for updates) which creates a startmenu entry.
