### ISSUE TITLE
Where are Settings Stored

### ISSUE THREAD

**Issue by CyberTacoX** [SIRprise/SSD-LED#7]
Hello! I just wanted to ask, where are the program's settings stored on the system? I didn't see any info on that in the documentation. (Or did I miss it?)

**Comment by SIRprise** [comment]
I never have seen a documentation for the place settings are saved by any application.
One reason I cannot guarantee the place is that it is a windows and not a application thing in this case. I'm using the Properties.Settings.Default-way to access and this is redirected from windows to anywhere. (see [https://stackoverflow.com/questions/1804302/where-is-the-data-for-properties-settings-default-saved/1804324](https://stackoverflow.com/questions/1804302/where-is-the-data-for-properties-settings-default-saved/1804324))

In my case I found the .config-file in the same folder the application is stored with same name as the exe, and with additional ".config" as extension. On my other computer it is in the %appdata%-folder. This is in my case: C:\Users\MyUsername\AppData\Local\SSD_LED\SSD-LED.exe_Url_njrugf4thsp4mef3m0jc4tyhuk03bcf2\1.0.3.0\user.config. Notice that the AppData-folder is hidden if you use default settings of the windows file explorer.

**Comment by CyberTacoX** [comment]
Interesting! Well, at minimum, knowing that it has a .config extension is extremely helpful, I can search for that. Cool, thank you very much! :-)
